/***************************************************************************************************************
 
 Copyright (c) 2016-2017 i2CAT Foundation. All rights reserved.
 Use of this source code is governed by the LICENSE file in the root of the source tree.
 
 ****************************************************************************************************************/

import UIKit

@objc class ConstantsExposedToObjC: NSObject {

    // List of constants that will be accesed from Objective-C classes
    
    let objc_IP = IP
    let objc_URL_BASE = URL_BASE
    let objc_BASIC_AUTH_STR = BASIC_AUTH_STR
    let objc_GCM_SANDBOX = GCM_SANDBOX
    
    let objc_SERVER_HOST_URL = SERVER_HOST_URL
    let objc_TURN_SERVER_ADDRESS_1 = TURN_SERVER_ADDRESS_1
    let objc_TURN_SERVER_1_USERNAME = TURN_SERVER_1_USERNAME
    let objc_TURN_SERVER_1_PASSWORD = TURN_SERVER_1_PASSWORD
    
    let objc_TURN_SERVER_ADDRESS_2 = TURN_SERVER_ADDRESS_2
    let objc_TURN_SERVER_2_USERNAME = TURN_SERVER_2_USERNAME
    let objc_TURN_SERVER_2_PASSWORD = TURN_SERVER_2_PASSWORD
    
    let objc_STUN_SERVER_ADDRESS = STUN_SERVER_ADDRESS
    
    
    let objc_URL_BODY = URL_BODY
    let objc_URL_CREATE_PUBLIC_USER = URL_CREATE_PUBLIC_USER
    let objc_URL_CREATE_EXIST_USER = URL_CREATE_EXIST_USER
    let objc_URL_CREATE_NEW_USER = URL_CREATE_NEW_USER
    let objc_URL_LOGIN = URL_LOGIN
    let objc_URL_CIRCLES_BELONG = URL_CIRCLES_BELONG
    let objc_URL_UPLOAD_CONTENT = URL_UPLOAD_CONTENT
    let objc_URL_GET_MESSAGES = URL_GET_MESSAGES
    let objc_URL_SEND_MESSAGE = URL_SEND_MESSAGE
    let objc_URL_ADD_DEVICE_INFO = URL_ADD_DEVICE_INFO
    let objc_URL_UPDATE_DEVICE_INFO = URL_UPDATE_DEVICE_INFO
    let objc_URL_UPDATE_USER_INFO = URL_UPDATE_USER_INFO
    let objc_URL_SET_PROFILE_PHOTO = URL_SET_PROFILE_PHOTO
    let objc_URL_GET_ALL_NOTIFICATIONS = URL_GET_ALL_NOTIFICATIONS
    
    let objc_SUCCESS = SUCCESS
    let objc_FAILURE = FAILURE
    let objc_JSON_HEADER_PUBLIC_REQUEST = JSON_HEADER_PUBLIC_REQUEST
    let objc_LOGIN_HEADER_REQUEST = LOGIN_HEADER_REQUEST
    let objc_MESSAGE_TYPE_IMAGE = MESSAGE_TYPE_IMAGE
    let objc_MESSAGE_TYPE_VIDEO = MESSAGE_TYPE_VIDEO
    let objc_MESSAGE_TYPE_TEXT = MESSAGE_TYPE_TEXT
    let objc_MESSAGE_TYPE_AUDIO = MESSAGE_TYPE_AUDIO
    
    
    let objc_PHOTO_MIME_PNG = PHOTO_MIME_PNG
    let objc_PHOTO_MIME_JPG = PHOTO_MIME_JPG
    let objc_VIDEO_MIME_MP4 = VIDEO_MIME_MP4
    let objc_AUDIO_MIME_AC3 = AUDIO_MIME_AC3
    
    let objc_USERNAME_SUFFIX = USERNAME_SUFFIX
    
    // HEX COLORS
    let objc_HEX_WHITE_BACKGROUND = HEX_WHITE_BACKGROUND
    let objc_HEX_DARK_WHITE_SEGMENT = HEX_DARK_WHITE_SEGMENT
    let objc_HEX_DARK_BACK_FOOTER = HEX_DARK_BACK_FOOTER
    let objc_HEX_DARK_GREY_MY_PHOTO_BTN = HEX_DARK_GREY_MY_PHOTO_BTN
    let objc_HEX_RED_BTN = HEX_RED_BTN
    let objc_HEX_GRAY_BTN = HEX_GRAY_BTN
    let objc_HEX_CELL_MSG_READ = HEX_CELL_MSG_READ
    let objc_HEX_DARK_GRAY_HEADER = HEX_DARK_GRAY_HEADER
    
    // INIT FEED TYPE CELL TYPES
    let objc_INIT_CELL_AUDIO_MSG = INIT_CELL_AUDIO_MSG
    let objc_INIT_CELL_VIDEO_MSG = INIT_CELL_VIDEO_MSG
    let objc_INIT_CELL_IMAGE_MSG = INIT_CELL_IMAGE_MSG
    let objc_INIT_CELL_NEW_MESSAGE = INIT_CELL_NEW_MESSAGE
    let objc_INIT_CELL_CONNECTED_TO = INIT_CELL_CONNECTED_TO
    let objc_INIT_CELL_DISCONNECTED_OF = INIT_CELL_DISCONNECTED_OF
    let objc_INIT_CELL_EVENT_SENT = INIT_CELL_EVENT_SENT
    let objc_INIT_CELL_EVENT_ACCEPTED = INIT_CELL_EVENT_ACCEPTED
    let objc_INIT_CELL_EVENT_REJECTED = INIT_CELL_EVENT_REJECTED
    let objc_INIT_CELL_EVENT_DELETED = INIT_CELL_EVENT_DELETED
    let objc_INIT_CELL_INCOMING_EVENT = INIT_CELL_INCOMING_EVENT
    let objc_INIT_CELL_LOST_CALL = INIT_CELL_LOST_CALL
    let objc_INIT_CELL_CALL_REALIZED = INIT_CELL_CALL_REALIZED
    
    
    // EVENTS STATES
    let objc_EVENT_STATE_PENDING = EVENT_STATE_PENDING
    let objc_EVENT_STATE_ACCEPTED = EVENT_STATE_ACCEPTED
    let objc_EVENT_STATE_REJECTED = EVENT_STATE_REJECTED
    
    // NOTIFICATION TYPE
    let objc_NOTI_NEW_EVENT = NOTI_NEW_EVENT
    let objc_NOTI_EVENT_ACCEPTED = NOTI_EVENT_ACCEPTED
    let objc_NOTI_EVENT_REJECTED = NOTI_EVENT_REJECTED
    let objc_NOTI_EVENT_UPDATED = NOTI_EVENT_UPDATED
    let objc_NOTI_EVENT_DELETED = NOTI_EVENT_DELETED
    let objc_NOTI_NEW_MESSAGE = NOTI_NEW_MESSAGE
    let objc_NOTI_INCOMING_CALL = NOTI_INCOMING_CALL
    let objc_NOTI_USER_UPDATED = NOTI_USER_UPDATED
    let objc_NOTI_USER_UNLINKED = NOTI_USER_UNLINKED
    
    
    // RELACIÓ PARENTIU
    let objc_RELATION_PARTNER = RELATION_PARTNER
    let objc_RELATION_CHILD = RELATION_CHILD
    let objc_RELATION_GRANDCHILD = RELATION_GRANDCHILD
    let objc_RELATION_CAREGIVER = RELATION_CAREGIVER
    let objc_RELATION_FRIEND = RELATION_FRIEND
    let objc_RELATION_VOLUNTEER = RELATION_VOLUNTEER
    let objc_RELATION_OTHER = RELATION_OTHER
    
    
    // VIDEOCALL
    
    let objc_CALL_WAIT_LIMIT = CALL_WAIT_LIMIT
    let objc_VIDEO_MAX_DURATION = VIDEO_MAX_DURATION
    
    // MISC
    
    let objc_DEFAULT_PROFILE_IMAGE = DEFAULT_PROFILE_IMAGE
    
    
}
